[project]
name = "learn-retrieval-augmented-generation"
version = "0.1.0"
description = "RAG creation step-by-step"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nltk==3.9.1",
]

[dependency-groups]
dev = [
    "ruff>=0.15.0",
]
